baseURL = 'https://channelliving.com'
languageCode = 'en'
title = 'Channel Living'
theme = 'PaperMod'

# Asset configuration for proper CSS loading
canonifyURLs = true
relativeURLs = false

[params]
  env = "production"
  title = "Channel Living"
  description = "A modern lifestyle and technology blog powered by Hugo and PaperMod theme"
  keywords = ["lifestyle", "technology", "blog", "modern living", "hugo", "papermod"]
  author = "Channel Living"
  
  # SEO improvements
  images = ["images/channel-living-og.jpg"]
  DateFormat = "January 2, 2006"
  
  defaultTheme = "auto"
  disableThemeToggle = false
  
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.homeInfoParams]
    Title = "Welcome! 👋"
    Content = "Welcome to Channel Living - your destination for modern lifestyle, technology insights, and inspiring content."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/"

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 30
  [[menu.main]]
    identifier = "privacy"
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 40
  [[menu.main]]
    identifier = "terms"
    name = "Terms"
    url = "/terms-and-conditions/"
    weight = 50

pygmentsUseClasses = true

# SEO and performance optimizations
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    lineNumbersInTable = true
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
